config/routes.rb
Issues::Application.routes.draw do

  devise_for :users

  resources :tasks
  resources :goals

  root :to => 'tasks#index'

  match '/tasks/goal/:id', :to => 'tasks#by_goal', :as => 'tasks_by_goal'

end

app/models/goal.rb
class Goal < ActiveRecord::Base

  belongs_to :user
  has_many :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user
  belongs_to :goal

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :tasks
  has_many :goals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_filter :authenticate_user!,
    :only => [:new, :create, :edit, :update, :destroy]

  def index
    @goals = Goal.all
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = current_user.goals.new
  end

  def create
    @goal = current_user.goals.new(params[:goal])
    if @goal.save
      redirect_to goals_path, :flash => { :success => "Goal created!" }
    else
      render 'new'
    end
  end

  def edit
    @goal = current_user.goals.new
  end

  def update
    @goal = current_user.goals.new
    if @goal.update_attributes(params[:goal])
      redirect_to goals_path, :flash => { :success => "Goal updated!" }
    else
      render 'edit'
    end
  end

  def destroy
    @goal = current_user.goals.find(params[:id])
    @goal.destroy
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authenticate_user!,
    :only => [:new, :create, :edit, :update, :destroy]

  def index
    @tasks = Task.all
    @goals = Goal.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def by_goal
    @goal = Goal.find(params[:id])
    @tasks = Task.where(:goal_id => @goal)
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.build(params[:task])
    @goal = Goal.find(params[:goal_id])
    @task.goal = @goal
    if @task.save
      redirect_to root_path, :flash => { :success => "Task created!" }
    else
      render 'new'
    end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to root_path, :flash => { :success => "Task updated!" }
    else
      render 'edit'
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/goals/_goal.html.erb
<div class="goal round">
  <%= link_to goal.name, goal_path(goal) %>
  <span class="created"><%= goal.created_at.strftime("%m/%d/%Y") %></span>
  <div class="description"><%= goal.description %></div>
</div>

app/views/goals/index.html.erb
<%= link_to "New Goal", new_goal_path %>

<% if @goals.any? %>
  <%= render @goals %>
<% end %>

app/views/goals/new.html.erb
<%= form_for(@goal) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <br />

  <div class="field">
    <%= f.label :description %> (Optional)
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Create Goal" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="round">
  <h1><%= link_to "Issues", root_path %></h1>

  <ul id="links">
    <li><%= link_to "Tasks", tasks_path %></li>
    <li><%= link_to "Goals", goals_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Issues</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="main" class="round">

  <div id="interface" class="round">

    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
	<%= value %>
      </div>
    <% end %>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </section>
</section>
</body>

</html>

app/views/tasks/_task.html.erb
<div class="task round">
  <%= link_to task.name, task_path(task), :class => "name" %>
  <span class="created"><%= task.created_at.strftime("%m/%d/%Y") %></span>
  <div class="description"><%= task.description %></div>
  <div class="actions">
    <%= link_to "Edit", edit_task_path(task) %>
    <%= link_to "Destroy", task_path(task), :confirm => "Are you sure?",
      :method => :delete %>
  </div>
</div>

app/views/tasks/by_goal.html.erb
<% if @tasks.any? %>
  <% @tasks.each do |task| %>
    <%= render(task) %>
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<form method="link" action="<%= new_task_path %>">
  <input type="submit" value="+ New Task" id="new-task" class="round" />
</form>

<% if @tasks.any? %>
  <div class="task-list">
    <%= render @tasks %>
  </div>
<% end %>

<% if @goals.any? %>
  <div class="goal-list">
    <% @goals.each do |goal| %>
      <div class="goal">
	<%= link_to goal.name, tasks_by_goal_path(goal) %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <br />

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :goals %>
    <%= select_tag :goal_id, options_from_collection_for_select(Goal.all,
      "id", "name") %>
  </div>

  <div class="actions">
    <%= f.submit "Create Task" %>
  </div>
<% end %>  

app/views/tasks/show.html.erb
<%= render @task %>